name: Ubuntu

on:
  push:
    branches:
      - master
      - compute-shader-renderer
  pull_request:
    branches:
      - master

jobs:
  build-x86_64:
    name: x86_64
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
      name: Check out sources
    - name: Install dependencies
      run: |
        sudo rm -f /etc/apt/sources.list.d/dotnetdev.list /etc/apt/sources.list.d/microsoft-prod.list
        sudo apt update
        sudo apt install --allow-downgrades cmake ninja-build extra-cmake-modules libpcap0.8-dev libsdl2-dev \
          qt6-{base,base-private,multimedia}-dev libslirp0 libslirp-dev libarchive-dev libzstd-dev libfuse2
    - name: Configure
      run: cmake -B build -G Ninja -DUSE_QT6=ON -DCMAKE_INSTALL_PREFIX=/usr
    - name: Build
      run: |
        make -j$(nproc --all)
        mkdir dist
        cp melonDS dist/khDaysMM
    - uses: actions/upload-artifact@v1
      with:
        name: khDaysMM-ubuntu-x86_64
        path: ${{runner.workspace}}/build/dist
